http:
  middlewares:
    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50
    middlewares-rate-relaxed:
      rateLimit:
        average: 500
        burst: 200
    middlewares-rate-strict:
      rateLimit:
        average: 20
        burst: 10